### ISSUE TITLE
Frequency and Duty Cycle Measurement

### ISSUE THREAD

**Issue by lcmcninch** [khoih-prog/RP2040_PWM#7]
The "[more information](https://github.com/khoih-prog/RP2040_PWM#more-useful-information-about-rp2040-pwm)" part of your readme talks about measuring PWM frequency and duty cycle. It doesn't appear that that functionality has been implemented in your library. Assuming I'm not overlooking it, I wonder, is that something that you have considered implementing?

If not, are you aware of any examples of it being done? I have some Arduino experience but low-level embedded programming isn't my strong suit, so before I delve into the C/C++ SDK to see if I can learn to do it that way, I'm wondering if there are any alternatives.

Thanks for any insight you can provide.

**Comment by khoih-prog** [comment]
Sorry no plan to implement those features, sucg as **measuring PWM frequency and duty cycle**

Good Luck,
