### ISSUE TITLE
Measuring Duty Cycle Example

### ISSUE THREAD

**Issue by JohnStabler** [khoih-prog/RP2040_PWM#8]
I can't seem to find an example of measuring the duty cycle (or frequency) of an input signal.

Could some example code be provided please?

**Comment by khoih-prog** [comment]
Sorry, I won't add that kind of example as you can easily use **Interrupt** to measure.

You can follow this [**Three Ways To Read A PWM Signal With Arduino**](https://www.benripley.com/diy/arduino/three-ways-to-read-a-pwm-signal-with-arduino/).
